### ISSUE TITLE
can't set krbspn and krbsrvname

### ISSUE THREAD

**Issue by Sireax** [otan/gopgkrb5#1]
Hello! I am currently trying to use your library along with pgx and pgconn. The thing is - I can't set neither krbspn nor krbsrvname parameter

### Code

```
package main

import (
	"context"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgx/v4"
	"github.com/otan/gopgkrb5"
	"github.com/sirupsen/logrus"
)

func init() {
	pgconn.RegisterGSSProvider(func() (pgconn.GSS, error) { return gopgkrb5.NewGSS() })
}

func main() {

	conf, err := pgx.ParseConfig("postgres://testuser@DOMAIN1.LOCAL:nopassword@postgres:5432/vault?krbsrvname=postgres1&sslmode=disable")
	if err != nil {
		panic(err)
	}

	logrus.Info(conf.Config.RuntimeParams)

	conn, err := pgx.ConnectConfig(context.Background(), conf)
	defer conn.Close(context.Background())
	if err != nil {
		panic(err)
	}

	res, err := conn.Query(context.Background(), "SELECT * FROM information_schema.tables;")
	if err != nil {
		panic(err)
	}
	logrus.Println(res.Values())
	return
}
```

And it panics with
**panic: failed to connect to `host=postgres user=testuser@DOMAIN1.LOCAL database=vault`: failed GSS auth (kerberos error (InitSecContext): [R
oot cause: KDC_Error] KDC_Error: TGS Exchange Error: kerberos error response from KDC when requesting for postgres/postgres: KRB Error: (7) 
KDC_ERR_S_PRINCIPAL_UNKNOWN Server not found in Kerberos database - LOOKING_UP_SERVER)**

The KDC works perfectly, because I can connect with GSSAPI using psql without any promlem. The thing is, when I try to override krbsrvname, it is not changing (as i can tell from panic message)

### Packages versions I am using:

```
github.com/jackc/pgconn v1.12.0
github.com/jackc/pgx/v4 v4.16.0
github.com/otan/gopgkrb5 v1.0.1
github.com/sirupsen/logrus v1.8.1
```

**Comment by otan** [comment]
sorry about that - thought i had tested it but apparently with the wrong SHA.
thanks for submitting the fix - i will try merge tests with everything after `pgconn` is fixed (it's very tricky due to how everything is in separated repos)

**Comment by Sireax** [comment]
I also noticed that there is no configuration for ccache file that will be used for connection (except for env variable KRBCCNAME). Could you please copy it to connection string? The problem is, we can't make multiple connections using different TGT's in one application

**Comment by otan** [comment]
i would encourage you to file that under a separate issue (or maybe `pgconn`) with an example of usage and expected behaviour. i'll be honest - i'm not totally familiar with krb5, i've merely appropriated the implementation from the lib/pq library.

**Comment by Sireax** [comment]
Sure
