### ISSUE TITLE
Unable to use GSSAPI encryption

### ISSUE THREAD

**Issue by Sireax** [otan/gopgkrb5#7]
I really don't know if it's something wrong with **gokrb5** library, or pgx, but just for sure I will duplicate issue from **pgx** library here: https://github.com/jackc/pgx/issues/1220

I am using kerberos authentication to connect to postgres. In pg_hba.conf there is a separate host type hostgssenc, which enables secure data transport between client and server. If I use this line:

host all all 0.0.0.0/0 gss include_realm=1 krb_realm=DOMAIN1.LOCAL

everything works fine. However, the connection is not secure.
If I change host to hostgssenc, I get this error:

failed to connect to host=postgres user=[testuser@DOMAIN1.LOCAL](mailto:testuser@DOMAIN1.LOCAL) database=vault: server error (FATAL: no pg_hba.conf entry for host "172.18.0.2", user "[testuser@DOMAIN1.LOCAL](mailto:testuser@DOMAIN1.LOCAL)", database "vault", no encryption (SQLSTATE 28000))

If I connect to postgres via psql, the connection becomes secure along with authentication.

**Comment by Sireax** [comment]
I tried to change DisablePAFXFAST and AssumePreAuthentication settings, but this makes no effect

**Comment by otan** [comment]
I wonder if this is a problem with http://github.com/jcmturner/gokrb5 itself
it's pretty premature

**Comment by Sireax** [comment]
As I can see from GSSAPI docs, it has Integrity mechanism, which allows to sign messages with some kind of hash. The question is, does gokrb5 support GSSAPI Integrity mechanism? I found some breadcrumbs in source code, but no documentation.

**Comment by Sireax** [comment]
Should I create another issue in **gokrb5**?

**Comment by otan** [comment]
You can, but it looks like that project is dead. Most likely you'll need to fork it and add functionality and make gopgkrb5 depend on the new version.

**Comment by Sireax** [comment]
Oh that's bad
